orbs:
    # the name of the orb we are using
    aws-code-deploy: circleci/aws-code-deploy@1.4.1
# the version of the yml
version: 2.1
# Workflows are used to partition jobs
workflows:
  # this is one workflow with a job defined
  # you can have more than one of it
  deploy_application:
    
    # jobs are used to perform actions i.e. run instructions
    jobs:
        # This is the name of the job being run
        # You can run more than one job
        # The job accepts the following parameters
        - aws-code-deploy/deploy:
            application-name: circleci-pipeline
            bundle-bucket: circleci-bucket-ex
            bundle-key: code/source
            deployment-group: deployment
            service-role-arn: arn:aws:iam::650448798570:role/circleci-role   
          